version: '3.8'

services:
  http:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: http
    environment:
      CGO_ENABLED: 1
    ports:
      - "8080:8080"

  cli:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: cli
    environment:
      CGO_ENABLED: 1

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672